info:
  contact:
    email: nospam@mailbox.org
  description: Covid API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Covid API
  version: 1.0.0-oas3
openapi: 3.0.2
paths:
  /incidence:
    get:
      parameters:
      - in: query
        name: region
        schema:
          type: string
      responses:
        '200':
          content:
            image/jpeg:
              schema:
                format: binary
                type: string
          description: the graph as JPEG
servers:
- description: Demo server
  url: https://testbed.dev.52north.org/covid
tags:
- description: Endpoints related to Covid
  name: Covid
